export default {
  '@PROFILE/ON_CHANGE': '@PROFILE/ON_CHANGE',
  '@PROFILE/SET_ERRORS': '@PROFILE/HAS_ERRORS',
  '@PROFILE/CLEAR_ERROR': '@PROFILE/CLEAR_ERROR',
  '@PROFILE/SET_INITIAL_STATE': '@PROFILE/SET_INITIAL_STATE'
}
