export default {
  '@SIGNUP/ON_CHANGE': '@SIGNUP/ON_CHANGE',
  '@SIGNUP/HAS_ERRORS': '@SIGNUP/HAS_ERRORS',
  '@SIGNUP/CLEAR_ERROR': '@SIGNUP/CLEAR_ERROR',
  '@SIGNUP/CLEAR_FORM': '@SIGNUP/CLEAR_FORM'
}
